/// Flutter icons DeepIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DeepIcon
///      fonts:
///       - asset: fonts/DeepIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class DeepIcon {
  DeepIcon._();

  static const _kFontFam = 'DeepIcon';

  static const IconData picture = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData time = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData qq = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData microblog = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData WeChat = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData video = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData person = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData password = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData iphone = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData location_outline = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData icon_more = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData face = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData notification = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData typeface = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData picture_outline = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData card = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData re_backout = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData backout = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData more_vertical = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData menua = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData search_large = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData friend_list = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData cai = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData zan = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData pause_circle = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData down = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData right = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData Selected = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData publish = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData man = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData man_woman = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData woman = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData message = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData man_select = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData man_woman_select = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData man_woman_line = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData woman_select = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData man_line = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData woman_line = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData cai_cover = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData select_picture = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData zan_cover = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData music = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData adress = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData set_icon = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData photograph = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData edit_head_portrait = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData eyes_close = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData eyes_opene = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData edit_line = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData next_song = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData play_outline = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData song_list = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData voice = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData previous_song = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData select_camera = const IconData(0xe842, fontFamily: _kFontFam);
}
